language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"

before_install:
    - sudo apt-get install opencc

script:
    - python setup.py -q nosetests

notifications:
    email: false
